scout_skid_steer_controller:
  ros__parameters:
    # Publish all joint states -----------------------------------
    scout_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Joint velocity controllers ---------------------------------
    scout_motor_fr_controller:
      type: velocity_controllers/JointVelocityController
      joint: scout_mini_wheel_1
      pid:
        p: 5.0
        i: 20.0
        d: 0.0
        i_clamp: 100.0

    scout_motor_fl_controller:
      type: velocity_controllers/JointVelocityController
      joint: scout_mini_wheel_2
      pid:
        p: 5.0
        i: 20.0
        d: 0.0
        i_clamp: 100.0

    scout_motor_rl_controller:
      type: velocity_controllers/JointVelocityController
      joint: scout_mini_wheel_3
      pid:
        p: 5.0
        i: 20.0
        d: 0.0
        i_clamp: 100.0

    scout_motor_rr_controller:
      type: velocity_controllers/JointVelocityController
      joint: scout_mini_wheel_4
      pid:
        p: 5.0
        i: 20.0
        d: 0.0
        i_clamp: 100.0